version: "3.3"
services:
  creations-api:    
    container_name: creations-api
    build:      
      context: ./creations/
      dockerfile: ./Dockerfile
    depends_on: [ postgresql ]        
    ports:
      - "8080:80"
  postgresql:
    image: "postgres:14.1-alpine"
    environment:
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mysecretpassword "
      name: "creations"
    restart: always   
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
volumes:
  db:
    driver: local